
default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: cap
  username: cap
  password: cap

test:
  <<: *default
  database: cap_test_test

production:
  <<: *default
  database: cap_test_production
  username: cap_test
  password: <%= ENV['CAP_TEST_DATABASE_PASSWORD'] %>
