# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b151000e0a4776a2e340b3b6c0fb0c5cf0cf2a2827bf5bc27227f312f883b7042e69277c901a8fa5d42fb03cc5c27d2924aa3ae2c607adbcfbf063c261f5251e

test:
  secret_key_base: 5a12173e3439cdaec1259ec06a3277c4e93498bf85b8e8146b1e55b14a38b0b617d2a09408104190805abb992ae99c01e15526f89a468e2342520f5692e12b23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
